// Seed data for demo mode. Realistic Hebrew content so the UI feels alive.

import { DEMO_USER_ID, DEMO_WORKSPACE_ID } from "./mode";

const now = () => new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400_000).toISOString();
const daysAhead = (n: number) => new Date(Date.now() + n * 86400_000).toISOString();
const today = () => new Date().toISOString().slice(0, 10);
const addDays = (n: number) => new Date(Date.now() + n * 86400_000).toISOString().slice(0, 10);

const USER_DANA = DEMO_USER_ID;
const USER_AMIR = "33333333-3333-4333-8333-333333333333";
const USER_YAEL = "44444444-4444-4444-8444-444444444444";

const PROFILES = [
  {
    id: USER_DANA,
    email: "dana@countme.app",
    full_name: "דנה כהן (אתה)",
    avatar_url: null,
    locale: "he-IL",
    created_at: daysAgo(60),
    updated_at: daysAgo(1),
  },
  {
    id: USER_AMIR,
    email: "amir@countme.app",
    full_name: "אמיר לוי",
    avatar_url: null,
    locale: "he-IL",
    created_at: daysAgo(55),
    updated_at: daysAgo(2),
  },
  {
    id: USER_YAEL,
    email: "yael@countme.app",
    full_name: "יעל ישראלי",
    avatar_url: null,
    locale: "he-IL",
    created_at: daysAgo(50),
    updated_at: daysAgo(1),
  },
];

const WORKSPACES = [
  {
    id: DEMO_WORKSPACE_ID,
    name: "countme",
    slug: "countme",
    owner_id: USER_DANA,
    created_at: daysAgo(60),
    updated_at: daysAgo(1),
  },
];

const WORKSPACE_MEMBERS = [
  { workspace_id: DEMO_WORKSPACE_ID, user_id: USER_DANA, role: "owner", joined_at: daysAgo(60) },
  { workspace_id: DEMO_WORKSPACE_ID, user_id: USER_AMIR, role: "admin", joined_at: daysAgo(55) },
  { workspace_id: DEMO_WORKSPACE_ID, user_id: USER_YAEL, role: "member", joined_at: daysAgo(50) },
];

const CHAN_GENERAL = "ch_general_00000000000000000001";
const CHAN_SALES = "ch_sales_0000000000000000000001";
const CHAN_DM_AMIR = "ch_dm_dana_amir_0000000000000001";

const CHANNELS = [
  {
    id: CHAN_GENERAL,
    workspace_id: DEMO_WORKSPACE_ID,
    name: "general",
    type: "channel",
    is_private: false,
    topic: "ערוץ ראשי",
    created_by: USER_DANA,
    created_at: daysAgo(60),
  },
  {
    id: CHAN_SALES,
    workspace_id: DEMO_WORKSPACE_ID,
    name: "sales",
    type: "channel",
    is_private: false,
    topic: "לידים, לקוחות, צינור מכירות",
    created_by: USER_DANA,
    created_at: daysAgo(40),
  },
  {
    id: CHAN_DM_AMIR,
    workspace_id: DEMO_WORKSPACE_ID,
    name: null,
    type: "dm",
    is_private: true,
    topic: null,
    created_by: USER_DANA,
    created_at: daysAgo(30),
  },
];

const CHANNEL_MEMBERS = [
  { channel_id: CHAN_GENERAL, user_id: USER_DANA, joined_at: daysAgo(60), last_read_at: now() },
  { channel_id: CHAN_GENERAL, user_id: USER_AMIR, joined_at: daysAgo(55), last_read_at: now() },
  { channel_id: CHAN_GENERAL, user_id: USER_YAEL, joined_at: daysAgo(50), last_read_at: now() },
  { channel_id: CHAN_SALES, user_id: USER_DANA, joined_at: daysAgo(40), last_read_at: now() },
  { channel_id: CHAN_SALES, user_id: USER_AMIR, joined_at: daysAgo(40), last_read_at: now() },
  { channel_id: CHAN_DM_AMIR, user_id: USER_DANA, joined_at: daysAgo(30), last_read_at: now() },
  { channel_id: CHAN_DM_AMIR, user_id: USER_AMIR, joined_at: daysAgo(30), last_read_at: now() },
];

const MESSAGES = [
  {
    id: "msg_001_000000000000000000000001",
    channel_id: CHAN_GENERAL,
    user_id: USER_DANA,
    content: { text: "בוקר טוב צוות! 👋 מתחילים שבוע חדש." },
    parent_message_id: null,
    attachments: [],
    created_at: daysAgo(3),
    edited_at: null,
  },
  {
    id: "msg_001_000000000000000000000002",
    channel_id: CHAN_GENERAL,
    user_id: USER_AMIR,
    content: { text: "בוקר אור. סיימתי את ה-OAuth ל-Google אתמול בלילה — זה עובד." },
    parent_message_id: null,
    attachments: [],
    created_at: daysAgo(3),
    edited_at: null,
  },
  {
    id: "msg_001_000000000000000000000003",
    channel_id: CHAN_GENERAL,
    user_id: USER_YAEL,
    content: { text: "מעולה. אני ממשיכה היום עם ה-pricing page." },
    parent_message_id: null,
    attachments: [],
    created_at: daysAgo(2),
    edited_at: null,
  },
  {
    id: "msg_001_000000000000000000000004",
    channel_id: CHAN_SALES,
    user_id: USER_DANA,
    content: { text: "פגישה עם EY נקבעה ל-21.5. צריך להכין הצעת מחיר עד יום ה׳." },
    parent_message_id: null,
    attachments: [],
    created_at: daysAgo(1),
    edited_at: null,
  },
  {
    id: "msg_001_000000000000000000000005",
    channel_id: CHAN_SALES,
    user_id: USER_AMIR,
    content: { text: "מתחיל לעבוד על זה. נצטרך גם דק לסיכום." },
    parent_message_id: null,
    attachments: [],
    created_at: daysAgo(1),
    edited_at: null,
  },
  {
    id: "msg_001_000000000000000000000006",
    channel_id: CHAN_DM_AMIR,
    user_id: USER_AMIR,
    content: { text: "תוכלי להעביר לי את הקובץ של ה-onboarding flow?" },
    parent_message_id: null,
    attachments: [],
    created_at: daysAgo(0.5),
    edited_at: null,
  },
];

const CONTACTS = [
  {
    id: "ct_ron_levin_000000000000000001",
    workspace_id: DEMO_WORKSPACE_ID,
    name: "רון לוין",
    company: "EY ישראל",
    role: "Partner — Tax Advisory",
    email: "ron.levin@ey.com",
    phone: "050-1234567",
    status: "qualified",
    tags: ["EY", "פרטנר", "מס"],
    notes: "פנייה ראשונית דרך פרופ' שרון מהאוניברסיטה.",
    source: "Momentum",
    created_by: USER_DANA,
    created_at: daysAgo(20),
    updated_at: daysAgo(1),
  },
  {
    id: "ct_michal_segev_00000000000000001",
    workspace_id: DEMO_WORKSPACE_ID,
    name: "מיכל שגב",
    company: "Wix",
    role: "Head of Product Marketing",
    email: "michal@wix.com",
    phone: "052-9876543",
    status: "lead",
    tags: ["שותפות", "tech"],
    notes: "פגשנו ב-ProductCon. מעוניינת בדמו.",
    source: "אירוע",
    created_by: USER_AMIR,
    created_at: daysAgo(10),
    updated_at: daysAgo(3),
  },
  {
    id: "ct_yossi_avraham_0000000000000001",
    workspace_id: DEMO_WORKSPACE_ID,
    name: "יוסי אברהם",
    company: "Avraham CPA",
    role: "רואה חשבון",
    email: "yossi@avraham-cpa.co.il",
    phone: "054-1112222",
    status: "customer",
    tags: ["רו״ח", "שותף"],
    notes: "ממליץ ללקוחות. עובד איתנו 6 חודשים.",
    source: "המלצה",
    created_by: USER_DANA,
    created_at: daysAgo(180),
    updated_at: daysAgo(5),
  },
  {
    id: "ct_sapir_din_000000000000000001",
    workspace_id: DEMO_WORKSPACE_ID,
    name: "ספיר דין",
    company: "Tribu",
    role: "Founder",
    email: "sapir@tribu.app",
    phone: null,
    status: "lead",
    tags: ["startup", "fintech"],
    notes: "פוטנציאל לפיילוט עם עצמאיות בקהילה שלה.",
    source: "Cold outreach",
    created_by: USER_YAEL,
    created_at: daysAgo(7),
    updated_at: daysAgo(2),
  },
  {
    id: "ct_oren_b_000000000000000000001",
    workspace_id: DEMO_WORKSPACE_ID,
    name: "אורן בר",
    company: "ברי קרייאטיב",
    role: "מאייר עצמאי",
    email: "oren@barcr.studio",
    phone: "050-3333444",
    status: "customer",
    tags: ["יוזר", "פיילוט"],
    notes: "אחד היוזרים הראשונים שהכניסו דאטה ל-1301.",
    source: "פיילוט",
    created_by: USER_DANA,
    created_at: daysAgo(45),
    updated_at: daysAgo(1),
  },
];

const CONTACT_ACTIVITIES = [
  {
    id: "ca_001_0000000000000000000000001",
    contact_id: "ct_ron_levin_000000000000000001",
    type: "meeting",
    body: "שיחת הכרות 30 דק׳. רון מתעניין בנושאים של דיוק חישוב מס למייקרו-עצמאים. שולח חומר רקע.",
    metadata: {},
    created_by: USER_DANA,
    occurred_at: daysAgo(5),
    created_at: daysAgo(5),
  },
  {
    id: "ca_001_0000000000000000000000002",
    contact_id: "ct_ron_levin_000000000000000001",
    type: "email",
    body: "שלחתי את ה-One Pager + סקיצת הדמו. ביקש שנעדכן עד יום ה׳.",
    metadata: {},
    created_by: USER_DANA,
    occurred_at: daysAgo(3),
    created_at: daysAgo(3),
  },
  {
    id: "ca_001_0000000000000000000000003",
    contact_id: "ct_michal_segev_00000000000000001",
    type: "note",
    body: "אינטרס חזק מצידה לחבר אותנו לפיצ׳ר חדש שהם בונים לעצמאים ב-Wix Pay.",
    metadata: {},
    created_by: USER_AMIR,
    occurred_at: daysAgo(2),
    created_at: daysAgo(2),
  },
  {
    id: "ca_001_0000000000000000000000004",
    contact_id: "ct_oren_b_000000000000000000001",
    type: "call",
    body: "ביקש פגישה לדבר על אינטגרציה לחשבוניות. סינכרנתי איתו ל-22.5.",
    metadata: {},
    created_by: USER_DANA,
    occurred_at: daysAgo(1),
    created_at: daysAgo(1),
  },
];

const PROJ_LAUNCH = "pj_launch_0000000000000000000001";
const PROJ_EY_DEMO = "pj_ey_demo_000000000000000000001";

const PROJECTS = [
  {
    id: PROJ_LAUNCH,
    workspace_id: DEMO_WORKSPACE_ID,
    name: "השקה ציבורית",
    color: "#1a84e8",
    contact_id: null,
    created_by: USER_DANA,
    created_at: daysAgo(30),
    updated_at: daysAgo(1),
  },
  {
    id: PROJ_EY_DEMO,
    workspace_id: DEMO_WORKSPACE_ID,
    name: "דמו ל-EY",
    color: "#10b981",
    contact_id: "ct_ron_levin_000000000000000001",
    created_by: USER_DANA,
    created_at: daysAgo(14),
    updated_at: daysAgo(1),
  },
];

const TASKS = [
  {
    id: "tk_landing_page_000000000000000001",
    project_id: PROJ_LAUNCH,
    title: "Landing page — design v2",
    description: "עיצוב מחדש של ה-landing כולל פירוט פיצ׳רים.",
    assignee_id: USER_YAEL,
    start_date: addDays(-7),
    end_date: addDays(2),
    status: "in_progress",
    progress: 60,
    parent_task_id: null,
    contact_id: null,
    position: 0,
    created_by: USER_DANA,
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
  },
  {
    id: "tk_landing_page_dev_00000000000001",
    project_id: PROJ_LAUNCH,
    title: "Landing page — מימוש",
    description: null,
    assignee_id: USER_AMIR,
    start_date: addDays(2),
    end_date: addDays(7),
    status: "todo",
    progress: 0,
    parent_task_id: null,
    contact_id: null,
    position: 1,
    created_by: USER_DANA,
    created_at: daysAgo(7),
    updated_at: daysAgo(7),
  },
  {
    id: "tk_pricing_00000000000000000000001",
    project_id: PROJ_LAUNCH,
    title: "Pricing strategy",
    description: "תמחור לעצמאי, פרילנסר, ושותפות עם רו״ח.",
    assignee_id: USER_DANA,
    start_date: addDays(-3),
    end_date: addDays(4),
    status: "in_progress",
    progress: 40,
    parent_task_id: null,
    contact_id: null,
    position: 2,
    created_by: USER_DANA,
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
  {
    id: "tk_form_1301_demo_000000000000001",
    project_id: PROJ_EY_DEMO,
    title: "טופס 1301 — שדות ועלות חיים",
    description: null,
    assignee_id: USER_DANA,
    start_date: addDays(-10),
    end_date: addDays(-2),
    status: "done",
    progress: 100,
    parent_task_id: null,
    contact_id: null,
    position: 0,
    created_by: USER_DANA,
    created_at: daysAgo(10),
    updated_at: daysAgo(2),
  },
  {
    id: "tk_pitch_deck_0000000000000000001",
    project_id: PROJ_EY_DEMO,
    title: "Pitch deck",
    description: "10 שקפים, התמקדות בנקודה של ׳מספרי המס נכונים בלי רו״ח׳.",
    assignee_id: USER_AMIR,
    start_date: addDays(-1),
    end_date: addDays(3),
    status: "in_progress",
    progress: 30,
    parent_task_id: null,
    contact_id: "ct_ron_levin_000000000000000001",
    position: 1,
    created_by: USER_DANA,
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: "tk_demo_rehearsal_00000000000000001",
    project_id: PROJ_EY_DEMO,
    title: "חזרה גנרלית לדמו",
    description: null,
    assignee_id: null,
    start_date: addDays(5),
    end_date: addDays(5),
    status: "todo",
    progress: 0,
    parent_task_id: null,
    contact_id: null,
    position: 2,
    created_by: USER_DANA,
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
];

const DOCUMENT_FOLDERS = [
  {
    id: "fl_sales_0000000000000000000000001",
    workspace_id: DEMO_WORKSPACE_ID,
    name: "מכירות",
    parent_folder_id: null,
    created_by: USER_DANA,
    created_at: daysAgo(20),
  },
  {
    id: "fl_product_000000000000000000000001",
    workspace_id: DEMO_WORKSPACE_ID,
    name: "מוצר",
    parent_folder_id: null,
    created_by: USER_DANA,
    created_at: daysAgo(20),
  },
];

const DOC_EY_PROPOSAL = "dc_ey_proposal_0000000000000000001";
const DOC_VISION = "dc_vision_0000000000000000000001";
const DOC_MEETING = "dc_meeting_notes_000000000000000001";

const DOCUMENTS = [
  {
    id: DOC_EY_PROPOSAL,
    workspace_id: DEMO_WORKSPACE_ID,
    folder_id: "fl_sales_0000000000000000000000001",
    title: "הצעת מחיר — EY",
    content: {
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1, textAlign: "right" }, content: [{ type: "text", text: "הצעת מחיר — countme × EY" }] },
        { type: "paragraph", attrs: { textAlign: "right" }, content: [{ type: "text", text: "לכבוד: רון לוין, EY" }] },
        { type: "paragraph", attrs: { textAlign: "right" }, content: [{ type: "text", text: `תאריך: ${new Intl.DateTimeFormat("he-IL").format(new Date())}` }] },
        { type: "heading", attrs: { level: 2, textAlign: "right" }, content: [{ type: "text", text: "תיאור העבודה" }] },
        { type: "paragraph", attrs: { textAlign: "right" }, content: [{ type: "text", text: "פיתוח אינטגרציה חכמה למילוי דו״ח 1301 לעצמאים בישראל, בליווי AI." }] },
        { type: "heading", attrs: { level: 2, textAlign: "right" }, content: [{ type: "text", text: "תוצרים" }] },
        { type: "bulletList", content: [
          { type: "listItem", content: [{ type: "paragraph", attrs: { textAlign: "right" }, content: [{ type: "text", text: "מערכת web עם 8 שדות-מפתח אוטומטיים" }] }] },
          { type: "listItem", content: [{ type: "paragraph", attrs: { textAlign: "right" }, content: [{ type: "text", text: "ממשק chat לשאלות חופשיות" }] }] },
          { type: "listItem", content: [{ type: "paragraph", attrs: { textAlign: "right" }, content: [{ type: "text", text: "תיעוד מלא של נוסחאות החישוב" }] }] },
        ]},
      ],
    },
    template_key: "proposal",
    contact_id: "ct_ron_levin_000000000000000001",
    created_by: USER_DANA,
    updated_by: USER_DANA,
    updated_at: daysAgo(1),
    created_at: daysAgo(2),
  },
  {
    id: DOC_VISION,
    workspace_id: DEMO_WORKSPACE_ID,
    folder_id: "fl_product_000000000000000000000001",
    title: "Vision One Pager",
    content: {
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1, textAlign: "right" }, content: [{ type: "text", text: "countme — Vision" }] },
        { type: "heading", attrs: { level: 2, textAlign: "right" }, content: [{ type: "text", text: "הבעיה" }] },
        { type: "paragraph", attrs: { textAlign: "right" }, content: [{ type: "text", text: "352K עצמאים בישראל מתחת לגיל 35 מבזבזים זמן וכסף על מילוי דו״חות מס. רוב הזמן באמצעות רו״ח." }] },
        { type: "heading", attrs: { level: 2, textAlign: "right" }, content: [{ type: "text", text: "הפתרון" }] },
        { type: "paragraph", attrs: { textAlign: "right" }, content: [{ type: "text", text: "מערכת AI שמלווה את העצמאי מ-A עד Z במילוי הדו״ח." }] },
      ],
    },
    template_key: "one-pager",
    contact_id: null,
    created_by: USER_DANA,
    updated_by: USER_AMIR,
    updated_at: daysAgo(4),
    created_at: daysAgo(15),
  },
  {
    id: DOC_MEETING,
    workspace_id: DEMO_WORKSPACE_ID,
    folder_id: null,
    title: `פרוטוקול ישיבת צוות — ${new Intl.DateTimeFormat("he-IL").format(new Date(Date.now() - 86400_000 * 2))}`,
    content: {
      type: "doc",
      content: [
        { type: "heading", attrs: { level: 1, textAlign: "right" }, content: [{ type: "text", text: "פרוטוקול ישיבת צוות" }] },
        { type: "heading", attrs: { level: 2, textAlign: "right" }, content: [{ type: "text", text: "החלטות" }] },
        { type: "bulletList", content: [
          { type: "listItem", content: [{ type: "paragraph", attrs: { textAlign: "right" }, content: [{ type: "text", text: "פגישה עם EY ב-21.5" }] }] },
          { type: "listItem", content: [{ type: "paragraph", attrs: { textAlign: "right" }, content: [{ type: "text", text: "Pricing — להחליט עד יום ה׳" }] }] },
        ]},
      ],
    },
    template_key: "meeting-notes",
    contact_id: null,
    created_by: USER_DANA,
    updated_by: USER_DANA,
    updated_at: daysAgo(2),
    created_at: daysAgo(2),
  },
];

const CALENDAR_EVENTS = [
  {
    id: "ev_ey_demo_000000000000000000000001",
    workspace_id: DEMO_WORKSPACE_ID,
    title: "דמו ל-EY",
    description: "ההצגה הראשית. רון + שני partners נוספים.",
    location: "Zoom",
    start_at: daysAhead(7),
    end_at: new Date(Date.now() + 7 * 86400_000 + 3600_000).toISOString(),
    all_day: false,
    color: "#10b981",
    contact_id: "ct_ron_levin_000000000000000001",
    task_id: null,
    google_event_id: null,
    google_calendar_id: null,
    google_etag: null,
    created_by: USER_DANA,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: "ev_team_weekly_0000000000000000001",
    workspace_id: DEMO_WORKSPACE_ID,
    title: "Team weekly",
    description: null,
    location: "המשרד",
    start_at: daysAhead(2),
    end_at: new Date(Date.now() + 2 * 86400_000 + 30 * 60_000).toISOString(),
    all_day: false,
    color: "#1a84e8",
    contact_id: null,
    task_id: null,
    google_event_id: null,
    google_calendar_id: null,
    google_etag: null,
    created_by: USER_DANA,
    created_at: daysAgo(15),
    updated_at: daysAgo(15),
  },
  {
    id: "ev_pricing_review_000000000000001",
    workspace_id: DEMO_WORKSPACE_ID,
    title: "Pricing review",
    description: "סקירה לפני יציאה החוצה.",
    location: null,
    start_at: daysAhead(3),
    end_at: new Date(Date.now() + 3 * 86400_000 + 90 * 60_000).toISOString(),
    all_day: false,
    color: "#f59e0b",
    contact_id: null,
    task_id: null,
    google_event_id: null,
    google_calendar_id: null,
    google_etag: null,
    created_by: USER_DANA,
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
];

const EVENT_ATTENDEES = [
  { id: "ea_001", event_id: "ev_ey_demo_000000000000000000000001", user_id: USER_DANA, external_email: null, response: "accepted" },
  { id: "ea_002", event_id: "ev_ey_demo_000000000000000000000001", user_id: USER_AMIR, external_email: null, response: "accepted" },
  { id: "ea_003", event_id: "ev_ey_demo_000000000000000000000001", user_id: null, external_email: "ron.levin@ey.com", response: "pending" },
  { id: "ea_004", event_id: "ev_team_weekly_0000000000000000001", user_id: USER_DANA, external_email: null, response: "accepted" },
  { id: "ea_005", event_id: "ev_team_weekly_0000000000000000001", user_id: USER_AMIR, external_email: null, response: "accepted" },
  { id: "ea_006", event_id: "ev_team_weekly_0000000000000000001", user_id: USER_YAEL, external_email: null, response: "accepted" },
];

/** All seeded rows, keyed by table. */
export function buildSeed(): Record<string, Record<string, unknown>[]> {
  return {
    profiles: structuredClone(PROFILES),
    workspaces: structuredClone(WORKSPACES),
    workspace_members: structuredClone(WORKSPACE_MEMBERS),
    invitations: [],
    channels: structuredClone(CHANNELS),
    channel_members: structuredClone(CHANNEL_MEMBERS),
    messages: structuredClone(MESSAGES),
    message_reactions: [],
    contacts: structuredClone(CONTACTS),
    contact_activities: structuredClone(CONTACT_ACTIVITIES),
    contact_owners: [],
    projects: structuredClone(PROJECTS),
    tasks: structuredClone(TASKS),
    task_dependencies: [],
    gantt_imports: [],
    document_folders: structuredClone(DOCUMENT_FOLDERS),
    documents: structuredClone(DOCUMENTS),
    document_versions: [],
    files: [],
    calendar_events: structuredClone(CALENDAR_EVENTS),
    event_attendees: structuredClone(EVENT_ATTENDEES),
    user_google_tokens: [],
  };
}

/** FK relationships used by select() join syntax. */
export const FK_RELATIONS: Record<string, Record<string, { table: string; col: string }>> = {
  workspace_members: { profile: { table: "profiles", col: "user_id" }, workspace: { table: "workspaces", col: "workspace_id" } },
  invitations: { workspace: { table: "workspaces", col: "workspace_id" } },
  channels: { creator: { table: "profiles", col: "created_by" } },
  channel_members: { profile: { table: "profiles", col: "user_id" } },
  messages: { author: { table: "profiles", col: "user_id" } },
  contacts: { creator: { table: "profiles", col: "created_by" } },
  contact_activities: { author: { table: "profiles", col: "created_by" } },
  projects: { contact: { table: "contacts", col: "contact_id" }, creator: { table: "profiles", col: "created_by" } },
  tasks: { project: { table: "projects", col: "project_id" }, assignee: { table: "profiles", col: "assignee_id" } },
  documents: {
    author: { table: "profiles", col: "created_by" },
    updated_by_profile: { table: "profiles", col: "updated_by" },
  },
  calendar_events: { contact: { table: "contacts", col: "contact_id" } },
  event_attendees: { user: { table: "profiles", col: "user_id" } },
};

export { USER_DANA, USER_AMIR, USER_YAEL };
